# This file is covered by the LICENSE file in the root of this project.
path:
  dataset_path : ""
  maps_path : ""
  label_path : ""
  sample_path : ""
  output_path : ""
  train_txt_path : ""
insertion:
  classes : ["Cyclist", "Pedestrian"]
  min_points :
    "Cyclist" : 40
    "Pedestrian" : 40
  random : True
  number_of_object : 2    # sum of objects if rondom is True
  number_of_classes : [5, 7]  # number of objects if random is False
  placement :
    "Cyclist" : "Road"
    "Pedestrian" : "Sidewalk"
  labels_shortcut:
    "Cyclist": "C"
    "Pedestrian": "P"

labels:
  "Road" : 40
  "Parking" : 44
  "Sidewalk" : 48
