path:
  dataset_path : ""
  maps_path : "" + "/maps/small/npz"
  annotation_path : ""
  bbox_path : ""
  output_path : ""
insertion:
  classes : [5, 6, 7]
  min_points :
    5 : 30
    6 : 20
    7 : 20
  random : True
  number_of_object : 10    # sum of objects if rondom is True
  number_of_classes : [1, 1, 1, 1, 1, 1]  # number of objects if random is False
  placement:
    5 : [1, 3]
    6 : [1, 3]
    7 : [2, 3]
  placement_labels:
    1: [18, 19]
    2: [22]
    3: [20]
  labels_shortcut:
    1: "c"
    2: "ov"
    3: "b"
    4: "t"
    5: "mc"
    6: "bc"
    7: "P"

labels:
  0 : "undefined"
  1 : "car"
  2 : "other-vehicle"
  3 : "bus"
  4 : "truck"
  5 : "motorcyclist"
  6 : "bicyclist"
  7 : "pedestrian"
  8 : "sign"
  9 : "traffic_light"
  10: "pole"
  14: "building"
  15: "vegetation"
  16: "tree_trunk"
  17: "curb"
  18: "road"
  19: "lane_marker"
  20: "walkable"
  21: "other_ground"
  22: "sidewalk"

color_map: # bgr
  0 : [0, 0, 0]
  1 : [245, 150, 100]
  2 : [30, 30, 255 ]
  3 : [200, 40, 255 ]
  4 : [90, 30, 150 ]
  5 : [255, 0, 255 ]
  6 : [255, 150, 255 ]
  7 : [30, 30, 255]
  8 : [245, 230, 100]
  9 : [0, 0, 255]
  10: [150, 240, 255]
  11: [150, 0, 0] #?
  14: [0, 200, 255]
  15: [0, 175, 0]
  16: [0, 60, 135]
  17: [175, 0, 175]
  18: [255, 0, 255]
  19: [170, 255, 150]
  20: [100, 0, 100]
  21: [75, 0, 175]
  22: [75, 0, 75]
